import { useMemo, useState } from 'react';
import { router } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ActivityIndicator, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Ionicons from '@expo/vector-icons/Ionicons';
import { LessonNode } from '../../components/path/LessonNode';
import { CatMascot } from '../../components/mascot/CatMascot';
import { DuoButton } from '../../components/ui/DuoButton';
import { Screen } from '../../components/ui/Screen';
import { StatPill } from '../../components/ui/StatPill';
import { courseApi } from '../../services/courseApi';
import { profileApi } from '../../services/profileApi';
import { useSound } from '../../providers/SoundProvider';
import { useTheme } from '../../providers/ThemeProvider';

function flagFor(code?:string|null){if(code==='spain')return'🇪🇸';if(code==='france')return'🇫🇷';return'🌐';}
const feature=(title:string,description:string,icon='sparkles')=>router.push({pathname:'/feature',params:{title,description,icon}});

export default function LearnScreen(){
 const {colors}=useTheme(); const qc=useQueryClient(); const [courseModal,setCourseModal]=useState(false); const insets=useSafeAreaInsets(); const {play}=useSound();
 const meQuery=useQuery({queryKey:['me'],queryFn:profileApi.me}); const coursesQuery=useQuery({queryKey:['courses'],queryFn:courseApi.list}); const activeCourse=meQuery.data?.activeCourse;
 const pathQuery=useQuery({queryKey:['path',activeCourse?.id],queryFn:()=>courseApi.path(activeCourse!.id),enabled:Boolean(activeCourse?.id)});
 const activateMutation=useMutation({mutationFn:courseApi.activate,onSuccess:async()=>{play('correct');await Promise.all([qc.invalidateQueries({queryKey:['me']}),qc.invalidateQueries({queryKey:['courses']}),qc.invalidateQueries({queryKey:['path']})]);setCourseModal(false);}});
 const allLessons=useMemo(()=>pathQuery.data?.sections.flatMap(s=>s.units.flatMap(u=>u.lessons))??[],[pathQuery.data]);
 if(meQuery.isLoading||coursesQuery.isLoading)return <Screen edges={['top','left','right']} style={{alignItems:'center',justifyContent:'center'}}><ActivityIndicator color={colors.green} size="large"/></Screen>;
 if(!activeCourse)return <Screen edges={['top','left','right']} style={{paddingHorizontal:24,paddingTop:12,justifyContent:'center'}}><View style={{alignItems:'center',marginBottom:18}}><CatMascot size={108} mood="thinking"/></View><Text style={{color:colors.textPrimary,fontSize:28,fontWeight:'900',textAlign:'center'}}>What do you want to learn?</Text><Text style={{color:colors.textSecondary,fontSize:15,fontWeight:'700',textAlign:'center',marginTop:7}}>Courses for English speakers</Text><View style={{gap:14,marginTop:30}}>{coursesQuery.data?.map(course=><Pressable key={course.id} onPress={()=>activateMutation.mutate(course.id)} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:15,padding:16,borderRadius:18,borderWidth:2,borderBottomWidth:pressed?2:5,borderColor:colors.border,backgroundColor:colors.surface,transform:[{translateY:pressed?3:0}]})}><Text style={{fontSize:36}}>{flagFor(course.flagKey)}</Text><View style={{flex:1}}><Text style={{color:colors.textPrimary,fontSize:18,fontWeight:'900'}}>{course.title}</Text><Text style={{color:colors.textSecondary,fontSize:13,fontWeight:'600',marginTop:3}}>English → {course.targetLanguageName}</Text></View><Ionicons name="chevron-forward" size={24} color={colors.textMuted}/></Pressable>)}</View></Screen>;
 return <Screen edges={['top','left','right']}>
  <View style={{minHeight:62,borderBottomWidth:2,borderBottomColor:colors.border,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:colors.background}}>
   <Pressable onPress={()=>setCourseModal(true)} style={{minWidth:54,flexDirection:'row',alignItems:'center',gap:1}}><Text style={{fontSize:29}}>{flagFor(activeCourse.flagKey)}</Text><Ionicons name="chevron-down" size={16} color={colors.textSecondary}/></Pressable>
   <StatPill icon="flame" value={meQuery.data?.stats.streak??0} color={colors.orange} onPress={()=>feature('Streak','Your streak grows when you complete at least one lesson each day.','flame')}/>
   <StatPill icon="flash" value={meQuery.data?.stats.energy.current??0} color={colors.blue} onPress={()=>router.push('/shop')}/>
   <StatPill icon="diamond" value={meQuery.data?.stats.gems??0} color={colors.blue} onPress={()=>router.push('/shop')}/>
  </View>
  {pathQuery.isLoading?<View style={{flex:1,alignItems:'center',justifyContent:'center'}}><ActivityIndicator color={colors.green} size="large"/></View>:<ScrollView contentContainerStyle={{paddingHorizontal:20,paddingTop:18,paddingBottom:105+insets.bottom}} showsVerticalScrollIndicator={false}>{pathQuery.data?.sections.map(section=><View key={section.id}><Pressable onPress={()=>feature(section.title,section.subtitle??'Keep learning to move through this section.','book')} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:14,backgroundColor:colors.green,borderRadius:18,borderBottomWidth:pressed?2:5,borderBottomColor:colors.greenPressed,paddingHorizontal:18,paddingVertical:16,marginBottom:26,transform:[{translateY:pressed?3:0}]})}><View style={{flex:1}}><Text style={{color:colors.white,fontSize:12,fontWeight:'900',opacity:.92,letterSpacing:.5}}>{section.title.toUpperCase()}</Text><Text style={{color:colors.white,fontSize:19,lineHeight:25,fontWeight:'900',marginTop:4}}>{section.subtitle??'Keep learning'}</Text></View><Ionicons name="book" size={30} color={colors.white}/></Pressable>{section.units.map(unit=><View key={unit.id} style={{alignItems:'center',marginBottom:24}}><View style={{alignSelf:'stretch',marginBottom:5}}><Text style={{color:colors.textPrimary,fontSize:17,fontWeight:'900'}}>{unit.title}</Text>{!!unit.description&&<Text style={{color:colors.textSecondary,fontSize:13,lineHeight:19,fontWeight:'600',marginTop:3}}>{unit.description}</Text>}</View>{unit.lessons.map(lesson=>{const i=allLessons.findIndex(x=>x.id===lesson.id);const pattern=[0,-58,-82,-48,12,58,80,42];return <LessonNode key={lesson.id} lesson={lesson} offset={pattern[i%pattern.length]} onPress={()=>router.push(`/lesson/${lesson.id}`)}/>;})}</View>)}</View>)}</ScrollView>}
  <Modal visible={courseModal} transparent animationType="fade" onRequestClose={()=>setCourseModal(false)}><Pressable style={{flex:1,backgroundColor:'rgba(0,0,0,.68)',justifyContent:'flex-end'}} onPress={()=>setCourseModal(false)}><Pressable style={{backgroundColor:colors.surfaceSoft,borderTopLeftRadius:26,borderTopRightRadius:26,borderWidth:2,borderBottomWidth:0,borderColor:colors.border,padding:18,paddingBottom:Math.max(insets.bottom,18),gap:12}}><View style={{width:42,height:5,borderRadius:3,backgroundColor:colors.borderLight,alignSelf:'center',marginBottom:4}}/><Text style={{color:colors.textPrimary,fontSize:22,fontWeight:'900'}}>My courses</Text><Text style={{color:colors.textSecondary,fontSize:13,fontWeight:'600',marginBottom:4}}>Switching keeps each course's progress separate.</Text>{coursesQuery.data?.map(course=><Pressable key={course.id} onPress={()=>activateMutation.mutate(course.id)} style={{minHeight:70,borderRadius:16,borderWidth:2,borderColor:course.isUserActive?colors.green:colors.border,flexDirection:'row',alignItems:'center',gap:14,paddingHorizontal:14,backgroundColor:course.isUserActive?colors.greenSoft:colors.surface}}><Text style={{fontSize:36}}>{flagFor(course.flagKey)}</Text><View style={{flex:1}}><Text style={{color:colors.textPrimary,fontSize:18,fontWeight:'900'}}>{course.title}</Text><Text style={{color:colors.textSecondary,fontSize:13,fontWeight:'600',marginTop:3}}>{course.courseXp} XP</Text></View>{course.isUserActive&&<Ionicons name="checkmark-circle" size={26} color={colors.green}/>}</Pressable>)}<DuoButton title="Done" variant="outline" onPress={()=>setCourseModal(false)}/></Pressable></Pressable></Modal>
 </Screen>;
}
