import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { Pressable, ScrollView, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Screen } from '../../components/ui/Screen';
import { profileApi } from '../../services/profileApi';
import { useTheme } from '../../providers/ThemeProvider';
import { useSound } from '../../providers/SoundProvider';

const openFeature=(title:string,description:string,icon:string)=>router.push({pathname:'/feature',params:{title,description,icon}});
export default function QuestsScreen(){
 const {colors}=useTheme(); const {play}=useSound(); const meQuery=useQuery({queryKey:['me'],queryFn:profileApi.me}); const xp=meQuery.data?.stats.xpTotal??0; const lessons=meQuery.data?.stats.lessonsCompleted??0; const streak=meQuery.data?.stats.streak??0;
 const quests=[{title:'Earn 20 XP',value:Math.min(xp,20),max:20,icon:'flash' as const,color:colors.yellow},{title:'Complete 2 lessons',value:Math.min(lessons,2),max:2,icon:'book' as const,color:colors.blue},{title:'Keep your streak going',value:Math.min(streak,1),max:1,icon:'flame' as const,color:colors.orange}];
 return <Screen edges={['top','left','right']}><ScrollView contentContainerStyle={{paddingHorizontal:20,paddingTop:12,paddingBottom:110}} showsVerticalScrollIndicator={false}>
  <Text style={{color:colors.textPrimary,fontSize:29,fontWeight:'900'}}>Quests</Text><Text style={{color:colors.textSecondary,fontSize:15,fontWeight:'800',marginTop:4}}>Today's goals</Text>
  <Pressable onPress={()=>{play('tap');openFeature('Daily reward','Complete all three daily quests to unlock a reward chest.','gift');}} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:13,borderRadius:18,borderWidth:2,borderBottomWidth:pressed?2:4,borderColor:colors.border,backgroundColor:colors.surface,padding:15,marginTop:22,transform:[{translateY:pressed?2:0}]})}><View style={{width:52,height:52,borderRadius:16,backgroundColor:colors.purpleSoft,alignItems:'center',justifyContent:'center'}}><Ionicons name="gift" size={30} color={colors.purple}/></View><View style={{flex:1}}><Text style={{color:colors.textPrimary,fontSize:17,fontWeight:'900'}}>Daily reward</Text><Text style={{color:colors.textSecondary,fontSize:12,lineHeight:17,fontWeight:'600',marginTop:3}}>Complete your quests to keep the momentum going.</Text></View><Ionicons name="chevron-forward" size={22} color={colors.textMuted}/></Pressable>
  <View style={{gap:11,marginTop:22}}>{quests.map(q=>{const progress=q.max?q.value/q.max:0;const done=progress>=1;return <Pressable key={q.title} onPress={()=>{play('tap');openFeature(q.title,done?'Quest complete. Nice work!':'Keep learning to finish this quest.','checkmark-circle');}} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:13,borderWidth:2,borderColor:colors.border,borderRadius:17,padding:14,backgroundColor:pressed?colors.surfaceRaised:colors.surface})}><View style={{width:48,height:48,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:done?colors.greenSoft:colors.surfaceRaised}}><Ionicons name={done?'checkmark':q.icon} size={28} color={done?colors.green:q.color}/></View><View style={{flex:1}}><Text style={{color:colors.textPrimary,fontWeight:'900',fontSize:15}}>{q.title}</Text><View style={{height:12,borderRadius:8,backgroundColor:colors.border,overflow:'hidden',marginTop:10}}><View style={{height:'100%',borderRadius:8,width:`${Math.max(5,progress*100)}%`,backgroundColor:done?colors.green:q.color}}/></View></View><Text style={{color:colors.textSecondary,fontWeight:'900',fontSize:12}}>{q.value}/{q.max}</Text></Pressable>;})}</View>
  <Pressable onPress={()=>{play('tap');openFeature('Friend Quests','Team up with a friend and complete a shared XP challenge.','people');}} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:13,borderTopWidth:2,borderColor:colors.border,marginTop:26,paddingTop:20,opacity:pressed?.6:1})}><Ionicons name="people" size={31} color={colors.blue}/><View style={{flex:1}}><Text style={{color:colors.textPrimary,fontSize:16,fontWeight:'900'}}>Friend Quests</Text><Text style={{color:colors.textSecondary,fontSize:12,lineHeight:17,fontWeight:'600',marginTop:3}}>Complete a shared weekly challenge with a friend.</Text></View><Ionicons name="chevron-forward" size={22} color={colors.textMuted}/></Pressable>
 </ScrollView></Screen>;
}
